<?php

namespace ContainerWfWqFwH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GmZBAJVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GmZBAJV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GmZBAJV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.i.oOYtW', NULL, 'Cannot determine controller argument for "App\\Controller\\CategoryController::getListCategory()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
        ]);
    }
}
