<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEClEvGD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEClEvGD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEClEvGD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEClEvGD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEClEvGD\App_KernelDevDebugContainer([
    'container.build_hash' => 'EClEvGD',
    'container.build_id' => 'cff38d38',
    'container.build_time' => 1652291688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEClEvGD');
